# A environment for postgresql plugin development
FROM postgres:16

# install some dependencies
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    postgresql-server-dev-all \
    git \
    vim \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src

# set the environment variables
ENV PGDATA /var/lib/postgresql/data
ENV PATH /usr/lib/postgresql/$(pg_config --version)/bin:$PATH

# cd to the source code directory
WORKDIR /usr/src/postseis

# expose the port
EXPOSE 5432

# start the postgres server
CMD ["postgres"]
